spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: admin
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    application:
      name: springcloud-provider-dept
mybatis-plus:
    mapper-locations: classpath:com/lx/spring/springcloud/mapper/xml/*.xml
    global-config:
        db-column-underline: true
    configuration:
        map-underscore-to-camel-case: true
        #log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
logging:
  level:
    com.lx.spring.springcloud: debug
server:
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001-hystrix
    prefer-ip-address: true
    #org.springframework.jdbc.datasource : debug
info:
  app.name: springcloud-provider-dept-8001
  company.name: www.dp.com
  build.artifactId: springcloud-provider-dept-hystrix-8001
  build.version: 1.0-SNAPSHOT
management:
  security:
    enabled: false

