server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gateway-9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: springcloud-zuul-gateway-9527
  company.name: www.dp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept #springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /dp

#  http://myzuul.com:9527/springcloud-provider-dept/dept/get/1
#  http://myzuul.com:9527/dp/mydept/dept/get/1

